services:
  php:
    build:
      context: .
      target: php-fpm
    volumes:
      - .:/var/www/wtc
  nginx:
    build:
      context: .
      target: nginx
    depends_on:
      - php
    volumes:
      - ./public:/var/www/wtc/public
    ports:
      - "80:80"
